name: position
description: "Position est une application qui permets de trouver des
  entreprises autour de vous."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  bloc_test: ^9.1.7
  cached_network_image: ^3.3.1
  chopper: ^8.0.0
  drift: ^2.18.0
  equatable: ^2.0.5
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5
  firebase_performance: ^0.9.4+5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  geolocator: ^11.0.0
  get_it: ^7.7.0
  hydrated_bloc: ^9.1.5
  intl: ^0.18.1
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  meta: ^1.11.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  sqlite3: ^2.4.3
  sqlite3_flutter_libs: ^0.5.21
dev_dependencies:
  build_runner: ^2.4.9
  change_app_package_name: ^1.1.0
  chopper_generator: ^8.0.0
  drift_dev: ^2.18.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/png/ic_launcher_foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/png/
    - assets/images/svg/
    - assets/images/categories/logo/
    - assets/images/categories/logo/map/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/Roboto-Regular.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/open_sans/Roboto-Bold.ttf
    - family: OpenSans-Light
      fonts:
        - asset: assets/fonts/open_sans/Roboto-Light.ttf
    - family: OpenSans-Semibold
      fonts:
        - asset: assets/fonts/open_sans/Roboto-Medium.ttf
    - family: OpenSans-Italic
      fonts:
        - asset: assets/fonts/open_sans/Roboto-Italic.ttf
flutter_intl:
  enabled: true
  class_name: PositionLocalizations
  main_locale: fr
